/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Blue Lantern (https://sketchfab.com/genoris2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-laptop-4e72a2078b3c4a75a821ab09830693fe
Title: Gaming Laptop
*/
"use client";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Laptop(props) {
  const { nodes, materials } = useGLTF("/models/gaming_laptop.glb");

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });

  return (
    <group {...props} dispose={null} ref={modelRef} 
    // rotation={[0.4, -1, 0]}
    position={[0, 0, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.001']}
        position={[-0.17, -0.018, 0]}
        rotation={[0, 0, -1.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials['Material.002']}
        position={[-0.17, -0.018, 0]}
        rotation={[0, 0, -1.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.003']}
        position={[-0.17, -0.018, 0]}
        rotation={[0, 0, -1.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials['Material.004']}
        position={[-0.17, -0.018, 0]}
        rotation={[0, 0, -1.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials['Material.005']}
        position={[-0.17, -0.018, 0]}
        rotation={[0, 0, -1.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials['Material.006']}
        position={[-0.17, -0.018, 0]}
        rotation={[0, 0, -1.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials['Material.007']}
        position={[-0.17, -0.018, 0]}
        rotation={[0, 0, -1.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials['Material.008']}
        position={[-0.17, -0.018, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials['Material.009']}
        position={[-0.17, -0.018, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials['Material.009']}
        position={[-0.17, -0.018, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials['Material.010']}
        position={[-0.17, -0.018, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials['Material.011']}
        position={[-0.17, -0.018, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials['Material.012']}
        position={[-0.17, -0.018, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials['Material.014']}
        position={[-0.17, -0.018, 0]}
      />
    </group>
  );
}

useGLTF.preload("models/gaming_laptop.glb");


// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/gaming_laptop_2.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_4.geometry}
//         material={materials['Material.001']}
//         position={[-0.17, -0.018, 0]}
//         rotation={[0, 0, -1.38]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_5.geometry}
//         material={materials['Material.002']}
//         position={[-0.17, -0.018, 0]}
//         rotation={[0, 0, -1.38]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_6.geometry}
//         material={materials['Material.003']}
//         position={[-0.17, -0.018, 0]}
//         rotation={[0, 0, -1.38]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_7.geometry}
//         material={materials['Material.004']}
//         position={[-0.17, -0.018, 0]}
//         rotation={[0, 0, -1.38]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_8.geometry}
//         material={materials['Material.005']}
//         position={[-0.17, -0.018, 0]}
//         rotation={[0, 0, -1.38]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_9.geometry}
//         material={materials['Material.006']}
//         position={[-0.17, -0.018, 0]}
//         rotation={[0, 0, -1.38]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_10.geometry}
//         material={materials['Material.007']}
//         position={[-0.17, -0.018, 0]}
//         rotation={[0, 0, -1.38]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_13.geometry}
//         material={materials['Material.008']}
//         position={[-0.17, -0.018, 0]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_14.geometry}
//         material={materials['Material.009']}
//         position={[-0.17, -0.018, 0]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_15.geometry}
//         material={materials['Material.009']}
//         position={[-0.17, -0.018, 0]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_16.geometry}
//         material={materials['Material.010']}
//         position={[-0.17, -0.018, 0]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_17.geometry}
//         material={materials['Material.011']}
//         position={[-0.17, -0.018, 0]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_18.geometry}
//         material={materials['Material.012']}
//         position={[-0.17, -0.018, 0]}
//       />
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_19.geometry}
//         material={materials['Material.014']}
//         position={[-0.17, -0.018, 0]}
//       />
//     </group>
//   )
// }

// useGLTF.preload("models/gaming_laptop.glb");